### ISSUE TITLE
Search options missing from /search/photos

### ISSUE THREAD

**Issue by janhenckens** [unsplash/unsplash-php#43]
Now that /photos/search has been deprecated in favour of /search/photos, I was wondering if there are any plans on adding the existing parameters to the new endpoint. (in particular the orientation and category options)

Thanks
(Already working on a PR to add the new search endpoint to this library so wanted to ask before I submit the PR)

**Comment by lukechesser** [comment]
Hey @janhenckens great question and thanks for contributing back :)

Categories are deprecated too, since they're not a part of product strategy going forward (as they've been replaced by collections) and require a lot of upkeep to maintain.

As for orientation, right now we don't have any immediate plans to add it, but I could definitely see us adding it at some point in the future, as well as a few other 'advanced' search options.

Does that help?

**Comment by janhenckens** [comment]
That helps :) I'll drop category search from the plugin I'm currently building.
I'm having some issues with the response from the new point and how it differs from the others in the php library but I'll open a new issue for that.

Cheers
Jan
